# Список пользователей.
GET  http://127.0.0.1:8000/api/users/?page=2
Content-Type: application/json

###
# Регистрация нового пользователя.
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "suhanoff@yandex.com",
"username": "suhoi",
"first_name": "Егор",
"last_name": "Суханоф",
"password": "12345abc!"
}

###
# Проверка на отстуствие обязательных полей или
# их некорректность,
# а также на регистрацию с уже существющими email и username.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{

}

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "podushkin@yandex.com",
"username": "me",
"first_name": "Artem",
"last_name": "Podushkin",
"password": "12345ab!"
}

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "pugovkin@yandex.com",
"username": "pugovica///otoRvaNnayA###",
"first_name": "Artem////pUgoVica###",
"last_name": "Pugovkin///pUgoVica###",
"password": "12345ab!"
}

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "pechkin@yandex.com",
"username": "pechka",
"first_name": "Евгений",
"last_name": "Печкин",
"password": "12345abc!"
}

###
# Получение токена авторизации.
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
"email": "suhanoff@yandex.com",
"password": "12345abc!"
}

###
# Удаление токена.
POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: Token 054e6bb2c6370b64a728afc66bccc097992b0e0a

###
# Проверка на удаления токена неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json

###
# Профиль пользователя.
GET  http://127.0.0.1:8000/api/users/3/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на запрос неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
GET  http://127.0.0.1:8000/api/users/1/
Content-Type: application/json

###
# Проверка запроса на несуществующего пользователя.
# Должна выбрасываться ошибка 404.
GET  http://127.0.0.1:8000/api/users/100500/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Текущий пользователь.
GET  http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на запрос неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
GET  http://127.0.0.1:8000/api/users/me/
Content-Type: application/json

###
# Изменение пароля.
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"new_password": "12345abcd!",
"current_password": "12345abc!"
}

###
# Проверка изменение пароля на невалидных данных
# и на отсутствие обязательных полей.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"new_password": "пароль",
"current_password": "12345abcd!"
}

###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"new_password": " ",
"current_password": " "
}

###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{

}

###
# Проверка изменения пароля неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json

{
"new_password": "12345abcde!",
"current_password": "12345abcd!"
}

###
# Список тегов.
GET  http://127.0.0.1:8000/api/tags/
Content-Type: application/json

###
# Получение тега.
GET  http://127.0.0.1:8000/api/tags/4/
Content-Type: application/json

###
# Проверка на несуществующий тег,
# Должна выбрасываться ошибка 404.
GET  http://127.0.0.1:8000/api/tags/100500/
Content-Type: application/json

###
# Список рецептов.
GET  http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Список рецептов.
# Проверка фильтрации списка покупок.
GET  http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=1
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Список рецептов.
# Проверка фильтрации списка избранного.
GET  http://127.0.0.1:8000/api/recipes/?is_favorited=1
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Список рецептов.
# Проверка фильтрации по тегам.
GET  http://127.0.0.1:8000/api/recipes/?tags=lunch&tags=breakfast
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка изменения лимита рецептов на одной странице.
GET  http://127.0.0.1:8000/api/recipes/?limit=10
Content-Type: application/json

###
# Проверка на пагинацию списка рецептов.
GET  http://127.0.0.1:8000/api/recipes/?limit=6&offset=6&page=2
Content-Type: application/json

###
# Создание рецепта.
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"ingredients": [
{
   "id": 2144,
   "amount": 2
},
{
   "id": 377,
   "amount": 50 
},
{
   "id": 2192,
   "amount": 50
},
{
   "id": 1647,
   "amount": 1
}
],
"tags": [
    5
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "фрукты",
"text": "ням ням",
"cooking_time": 20
}



###
# Проверка на отсутствие обязательных полей.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{

}

###
# Проверка создания рецепта из несуществующих данных.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"ingredients": [
{
   "id": 100500,
   "amount": 50
},
{
   "id": 100500,
   "amount": 200 
}
],
"tags": [
    8
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "воздух",
"text": "ням ням",
"cooking_time": 5
}

###
# Проверка ограничения на минимальное время приготовления.
# Должна выбрасываться ошибка 400. 
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"ingredients": [
{
   "id": 656,
   "amount": 100
},
{
   "id": 1989,
   "amount": 200 
}
],
"tags": [
    5
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "бутерброды с колбаской копченой",
"text": "ням ням",
"cooking_time": 0
}

###
# Проверка на отсутствие обязательных полей id и amount.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"ingredients": [
{

}
],
"tags": [
    4
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "каша ячменная",
"text": "завтрак чемпиона",
"cooking_time": 7
}

###
# Проверка на создание рецепта неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json

{
"ingredients": [
{
"id": 2185,
"amount": 50
}
],
"tags": [
    4
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "каша ячменная",
"text": "завтрак чемпиона",
"cooking_time": 7
}

###
# Проверка создания рецепта из одинаковых ингредиентов.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"ingredients": [
{
   "id": 2185,
   "amount": 50
},
{
   "id": 2185,
   "amount": 200 
}
],
"tags": [
    4
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "воздух",
"text": "ням ням",
"cooking_time": 5
}

###
# Получение рецепта.
GET http://127.0.0.1:8000/api/recipes/12/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Получение рецепта неавторизованным пользователем.
GET http://127.0.0.1:8000/api/recipes/12/
Content-Type: application/json

###
# Обновление рецепта.
PATCH http://127.0.0.1:8000/api/recipes/18/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"ingredients": [
{
   "id": 1991,
   "amount": 50
},
{
   "id": 251,
   "amount": 200 
}
],
"tags": [
    4
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "бутерброд студенческий из белого хлеба",
"text": "раз-раз и готово",
"cooking_time": 1
}

###
# Обновление рецепта.
# Ошибки в ингредиентах.
# В приведенном примере в первом и третьем ингредиенте
# не было ошибок (amount >= 1), а во втором были.
# Должна выбрасываться ошибка 400.
PATCH http://127.0.0.1:8000/api/recipes/18/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{
"ingredients": [
{
   "id": 1137,
   "amount": 100
},
{
   "id": 898,
   "amount": 0
},
{
   "id": 1341,
   "amount": 100
}
],
"tags": [
    5
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "салат",
"text": "накрашил аля улю и готово",
"cooking_time": 1
}

###
# Обновление рецепта.
# Проверка обновления рецепта при отсутствии обязательных полей.
PATCH http://127.0.0.1:8000/api/recipes/18/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

{

}

###
# Проверка обновления рецепта неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
PATCH http://127.0.0.1:8000/api/recipes/11/
Content-Type: application/json

{
"ingredients": [
{
   "id": 1997,
   "amount": 50
},
{
   "id": 251,
   "amount": 200 
}
],
"tags": [
    4
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "бутерброд студенческий из ржаного хлеба",
"text": "раз-раз и готово",
"cooking_time": 1
}

###
# Проверка обновления рецепта не его автором.
# Недостаточно прав.
# Должна выбрасываться ошибка 403.
PATCH http://127.0.0.1:8000/api/recipes/18/
Content-Type: application/json
Authorization: Token 5698666e66a0cb1dfd024a5b8c309a204a32a8a1


{
"ingredients": [
{
   "id": 1997,
   "amount": 50
},
{
   "id": 251,
   "amount": 200 
}
],
"tags": [
    4
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "бутерброд студенческий из ржаного хлеба",
"text": "раз-раз и готово",
"cooking_time": 1
}

###
# Проверка обновления несуществующего рецепта.
# Должна выбрасываться ошибка 404.
PATCH http://127.0.0.1:8000/api/recipes/100500/
Content-Type: application/json
Authorization: Token fdea94cf817a47e95f39b02fe1d9473f5b8a547b


{
"ingredients": [
{
   "id": 1997,
   "amount": 50
},
{
   "id": 251,
   "amount": 200 
}
],
"tags": [
    4
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "бутерброд студенческий из ржаного хлеба",
"text": "раз-раз и готово",
"cooking_time": 1
}

###
# Удаление рецепта.
DELETE http://127.0.0.1:8000/api/recipes/18/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на удаление рецепта неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
DELETE http://127.0.0.1:8000/api/recipes/10/
Content-Type: application/json

###
# Проверка на удаление рецепта не его автором.
# Должна выбрасываться ошибка 403.
DELETE http://127.0.0.1:8000/api/recipes/10/
Content-Type: application/json
Authorization: Token fdea94cf817a47e95f39b02fe1d9473f5b8a547b

###
# Проверка на удаление несуществующего рецепта.
# Должна выбрасываться ошибка 404.
DELETE http://127.0.0.1:8000/api/recipes/100500/
Content-Type: application/json
Authorization: Token fdea94cf817a47e95f39b02fe1d9473f5b8a547b

###
# Добавление рецепта в список покупок.
POST http://127.0.0.1:8000/api/recipes/5/shopping_cart/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на добавление уже ранее добавленного рецепта в список покупок.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/recipes/7/shopping_cart/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на добавление рецепта
# в список покупок неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
POST http://127.0.0.1:8000/api/recipes/5/shopping_cart/
Content-Type: application/json

###
# Скачивание списка покупок.
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка скачивания списка покупок неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Content-Type: application/json

###
# Удаление рецепта из списка покупок.
DELETE http://127.0.0.1:8000/api/recipes/7/shopping_cart/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на удаление рецепта из списка покупок,
# когда его там не было.
# Должна выбрасываться ошибка 400.
DELETE http://127.0.0.1:8000/api/recipes/15/shopping_cart/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на удаления рецепта из списка покупок
# неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
DELETE http://127.0.0.1:8000/api/recipes/8/shopping_cart/
Content-Type: application/json

###
# Добавление рецепта в список избранное.
POST http://127.0.0.1:8000/api/recipes/5/favorite/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на добавление уже ранее добавленного рецепта в список избранное.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/recipes/7/favorite/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на добавление рецепта
# в список избранного неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
POST http://127.0.0.1:8000/api/recipes/7/favorite/
Content-Type: application/json

###
# Удаление рецепта из списка избранного.
DELETE http://127.0.0.1:8000/api/recipes/7/favorite/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на удаление рецепта из списка избранного,
# когда его там не было.
# Должна выбрасываться ошибка 400.
DELETE http://127.0.0.1:8000/api/recipes/15/favorite/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка на удаления рецепта из избранного
# неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
DELETE http://127.0.0.1:8000/api/recipes/15/favorite/
Content-Type: application/json

###
# Подписаться на пользователя. Проверка лимита рецептов.
POST http://127.0.0.1:8000/api/users/5/subscribe/?recipes_limit=2
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Подписаться на пользователя.
# Проверка лимита рецептов числом с плавающей точкой.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/users/1/subscribe/?recipes_limit=2.5
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка подписки на пользователя на которого уже подписан.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/users/5/subscribe/?recipes_limit=2
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка подписки на самого себя.
# Должна выбрасываться ошибка 400.
POST http://127.0.0.1:8000/api/users/8/subscribe/
Content-Type: application/json
Authorization: Token fdea94cf817a47e95f39b02fe1d9473f5b8a547b

###
# Проверка подписки неавторизованного пользователя на автора.
# Должна выбрасываться ошибка 401.
POST http://127.0.0.1:8000/api/users/2/subscribe/
Content-Type: application/json

###
# Проверка подписки на несуществующего пользователя.
# Должна выбрасываться ошибка 404.
POST http://127.0.0.1:8000/api/users/100500/subscribe/?recipes_limit=2
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Мои подписки.
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка запрса подписок неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json

###
# Отписаться от пользователя.
DELETE http://127.0.0.1:8000/api/users/1/subscribe/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка отписки от пользователя на которого не был подписан.
# Должна выбрасываться ошибка 400.
DELETE http://127.0.0.1:8000/api/users/2/subscribe/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Проверка отписки от автора неавторизованным пользователем.
# Должна выбрасываться ошибка 401.
DELETE http://127.0.0.1:8000/api/users/2/subscribe/
Content-Type: application/json

###
# Проверка отписки от несуществующего пользователя.
# Должна выбрасываться ошибка 404.
DELETE http://127.0.0.1:8000/api/users/100500/subscribe/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Список ингредиентов.
# Проверка поиска по частичному вхождению в начале названия ингредиента.
GET http://127.0.0.1:8000/api/ingredients/?name=паста
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001

###
# Получение ингредиента.
GET http://127.0.0.1:8000/api/ingredients/28/
Content-Type: application/json
Authorization: Token 9f2dff3a648dccec89ad1de8cf760bf544a02001
