# Generated by Django 3.2.15 on 2023-07-17 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorit',
            new_name='Favorite',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Добавьте изображение рецепта!', upload_to='recipes/images/', verbose_name='Изображение рецепта'),
        ),
    ]
