# Generated by Django 3.2.15 on 2023-07-22 23:57

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230722_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите название ингредиента!', max_length=200, validators=[api.validators.validate_name], verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Укажите название рецепта!', max_length=200, validators=[api.validators.validate_name], verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Укажите цвет тега!', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#([a-fA-F0-9]{3,6})$', message='Введите корректный код цвета например #ff0000.')], verbose_name='Цвет тега в HEX'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Укажите название тега!', max_length=200, unique=True, validators=[api.validators.validate_name], verbose_name='Название тега'),
        ),
    ]
