# Generated by Django 3.2.15 on 2023-07-21 19:05

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Укажите имя!', max_length=150, validators=[api.validators.validate_first_last_name], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Укажите фамилию!', max_length=150, validators=[api.validators.validate_first_last_name], verbose_name='Фамилия пользователя'),
        ),
    ]
